In [47]:
import tensorflow as tf
import numpy as np

from tensorflow import keras

print(tf.__version__)

2.8.0


In [48]:
model = keras.Sequential([
  keras.layers.Dense(units=1, input_shape=[1])
])

sgd = tf.keras.optimizers.SGD(learning_rate=0.005)
model.compile(loss='mean_squared_error', optimizer=sgd)

In [49]:
house_prices = np.array([
  [0.2, 0.2],
  [1, 1.8],
  [2, 4],
  [3, 7],
  [4, 9],
  [5, 11],
  [7, 12],
  [10, 13],
  [9, 14]
])

x = house_prices[:, [0]]
y = house_prices[:, [1]]

house_prices

array([[ 0.2,  0.2],
       [ 1. ,  1.8],
       [ 2. ,  4. ],
       [ 3. ,  7. ],
       [ 4. ,  9. ],
       [ 5. , 11. ],
       [ 7. , 12. ],
       [10. , 13. ],
       [ 9. , 14. ]])

In [50]:
x

array([[ 0.2],
       [ 1. ],
       [ 2. ],
       [ 3. ],
       [ 4. ],
       [ 5. ],
       [ 7. ],
       [10. ],
       [ 9. ]])

In [51]:
y

array([[ 0.2],
       [ 1.8],
       [ 4. ],
       [ 7. ],
       [ 9. ],
       [11. ],
       [12. ],
       [13. ],
       [14. ]])

In [52]:
model.fit(x, y, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 148ms/step - loss: 14.1961
Epoch 2/500
1/1 [==============================] - 0s 3ms/step - loss: 8.3075
Epoch 3/500
1/1 [==============================] - 0s 3ms/step - loss: 5.6086
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 4.3699
Epoch 5/500
1/1 [==============================] - 0s 2ms/step - loss: 3.7996
Epoch 6/500
1/1 [==============================] - 0s 3ms/step - loss: 3.5354
Epoch 7/500
1/1 [==============================] - 0s 2ms/step - loss: 3.4113
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 3.3514
Epoch 9/500
1/1 [==============================] - 0s 3ms/step - loss: 3.3208
Epoch 10/500
1/1 [==============================] - 0s 3ms/step - loss: 3.3038
Epoch 11/500
1/1 [==============================] - 0s 2ms/step - loss: 3.2929
Epoch 12/500
1/1 [==============================] - 0s 2ms/step - loss: 3.2849
Epoch 13/500
1/1 [==============================] - 0s 2ms

In [53]:
model.predict(np.array([
  [8],
  [12]
]))

array([[12.745376],
       [18.412672]], dtype=float32)

In [54]:
np.array(model.layers[0].weights, dtype=object)

array([[1.4168236255645752],
       [1.4107869863510132]], dtype=object)