In [30]:
import tensorflow as tf
import numpy as np

from tensorflow import keras

print(tf.__version__)

2.8.0


In [31]:
model = keras.Sequential([
  keras.layers.Dense(units=1, input_shape=[1])
])

model.compile(
  loss=tf.keras.losses.MeanSquaredError(), 
  optimizer=tf.keras.optimizers.SGD(learning_rate=0.005)
)

In [32]:
house_prices = np.array([
  [0.2, 0.2],
  [1, 1.8],
  [2, 4],
  [3, 7],
  [4, 9],
  [5, 11],
  [7, 12],
  [10, 13],
  [9, 14]
])

x = house_prices[:, [0]]
y = house_prices[:, [1]]

house_prices

array([[ 0.2,  0.2],
       [ 1. ,  1.8],
       [ 2. ,  4. ],
       [ 3. ,  7. ],
       [ 4. ,  9. ],
       [ 5. , 11. ],
       [ 7. , 12. ],
       [10. , 13. ],
       [ 9. , 14. ]])

In [33]:
x

array([[ 0.2],
       [ 1. ],
       [ 2. ],
       [ 3. ],
       [ 4. ],
       [ 5. ],
       [ 7. ],
       [10. ],
       [ 9. ]])

In [34]:
y

array([[ 0.2],
       [ 1.8],
       [ 4. ],
       [ 7. ],
       [ 9. ],
       [11. ],
       [12. ],
       [13. ],
       [14. ]])

In [35]:
model.fit(x, y, epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 551ms/step - loss: 239.7370
Epoch 2/500
1/1 [==============================] - 0s 6ms/step - loss: 111.3926
Epoch 3/500
1/1 [==============================] - 0s 7ms/step - loss: 52.6356
Epoch 4/500
1/1 [==============================] - 0s 13ms/step - loss: 25.7351
Epoch 5/500
1/1 [==============================] - 0s 7ms/step - loss: 13.4182
Epoch 6/500
1/1 [==============================] - 0s 9ms/step - loss: 7.7776
Epoch 7/500
1/1 [==============================] - 0s 8ms/step - loss: 5.1933
Epoch 8/500
1/1 [==============================] - 0s 10ms/step - loss: 4.0082
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 3.4636
Epoch 10/500
1/1 [==============================] - 0s 7ms/step - loss: 3.2122
Epoch 11/500
1/1 [==============================] - 0s 9ms/step - loss: 3.0952
Epoch 12/500
1/1 [==============================] - 0s 7ms/step - loss: 3.0396
Epoch 13/500
1/1 [==============================] 

In [36]:
model.predict(np.array([
  [8],
  [12]
]))

array([[12.73552 ],
       [18.368652]], dtype=float32)

In [37]:
np.array(model.layers[0].weights, dtype=object)

array([[1.4082832336425781],
       [1.469254493713379]], dtype=object)