In this workshop, you'll predict the salary of an applicant, given the data of other
applicants and the salary they're offered.

- `column 1:` [Microsoft Python Certification Exam][1] score
- `column 3:` years experience
- `column 4:` monthly salary offered, $x100,000$ pesos

> 👀 large values like the salary need to be scaled down, otherwise your MSE will be very very high
> Remember that before getting the average, we get the SUM first
> and sum of square of LARGE numbers can go towards $\infty$

[1]: https://www.udemy.com/course/microsoft-python-certification-exam-98-381-practice-tests/

In [77]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

import tensorflow as tf
from tensorflow import keras
from random import randrange

# display 3 places, suppress scientific notation
np.set_printoptions(precision=3, suppress=True)

X = np.array([[i, j, (i * 2.8 + j * 0.7 - randrange(-5, 6)) / 100] for i in range(28, 41) for j in range(1, 13)])
X

array([[28.   ,  1.   ,  0.781],
       [28.   ,  2.   ,  0.808],
       [28.   ,  3.   ,  0.775],
       [28.   ,  4.   ,  0.762],
       [28.   ,  5.   ,  0.819],
       [28.   ,  6.   ,  0.806],
       [28.   ,  7.   ,  0.803],
       [28.   ,  8.   ,  0.79 ],
       [28.   ,  9.   ,  0.807],
       [28.   , 10.   ,  0.824],
       [28.   , 11.   ,  0.821],
       [28.   , 12.   ,  0.918],
       [29.   ,  1.   ,  0.799],
       [29.   ,  2.   ,  0.786],
       [29.   ,  3.   ,  0.823],
       [29.   ,  4.   ,  0.83 ],
       [29.   ,  5.   ,  0.837],
       [29.   ,  6.   ,  0.854],
       [29.   ,  7.   ,  0.911],
       [29.   ,  8.   ,  0.888],
       [29.   ,  9.   ,  0.855],
       [29.   , 10.   ,  0.862],
       [29.   , 11.   ,  0.939],
       [29.   , 12.   ,  0.866],
       [30.   ,  1.   ,  0.857],
       [30.   ,  2.   ,  0.894],
       [30.   ,  3.   ,  0.821],
       [30.   ,  4.   ,  0.888],
       [30.   ,  5.   ,  0.825],
       [30.   ,  6.   ,  0.862],
       [30

In [78]:
# score, exp, ML, salary
data = np.array([
    [28.   ,  1.   ,  0.801],
    [28.   ,  2.   ,  0.758],
    [28.   ,  3.   ,  0.785],
    [28.   ,  4.   ,  0.862],
    [28.   ,  5.   ,  0.799],
    [28.   ,  6.   ,  0.836],
    [28.   ,  7.   ,  0.783],
    [28.   ,  8.   ,  0.8  ],
    [28.   ,  9.   ,  0.887],
    [28.   , 10.   ,  0.904],
    [28.   , 11.   ,  0.831],
    [28.   , 12.   ,  0.848],
    [29.   ,  1.   ,  0.839],
    [29.   ,  2.   ,  0.836],
    [29.   ,  3.   ,  0.803],
    [29.   ,  4.   ,  0.83 ],
    [29.   ,  5.   ,  0.877],
    [29.   ,  6.   ,  0.884],
    [29.   ,  7.   ,  0.871],
    [29.   ,  8.   ,  0.888],
    [29.   ,  9.   ,  0.915],
    [29.   , 10.   ,  0.912],
    [29.   , 11.   ,  0.859],
    [29.   , 12.   ,  0.876],
    [30.   ,  1.   ,  0.857],
    [30.   ,  2.   ,  0.854],
    [30.   ,  3.   ,  0.841],
    [30.   ,  4.   ,  0.818],
    [30.   ,  5.   ,  0.825],
    [30.   ,  6.   ,  0.852],
    [30.   ,  7.   ,  0.849],
    [30.   ,  8.   ,  0.876],
    [30.   ,  9.   ,  0.873],
    [30.   , 10.   ,  0.88 ],
    [30.   , 11.   ,  0.947],
    [30.   , 12.   ,  0.964],
    [31.   ,  1.   ,  0.825],
    [31.   ,  2.   ,  0.912],
    [31.   ,  3.   ,  0.909],
    [31.   ,  4.   ,  0.856],
    [31.   ,  5.   ,  0.893],
    [31.   ,  6.   ,  0.91 ],
    [31.   ,  7.   ,  0.867],
    [31.   ,  8.   ,  0.974],
    [31.   ,  9.   ,  0.921],
    [31.   , 10.   ,  0.888],
    [31.   , 11.   ,  0.905],
    [31.   , 12.   ,  0.952],
    [32.   ,  1.   ,  0.943],
    [32.   ,  2.   ,  0.88 ],
    [32.   ,  3.   ,  0.877],
    [32.   ,  4.   ,  0.904],
    [32.   ,  5.   ,  0.891],
    [32.   ,  6.   ,  0.898],
    [32.   ,  7.   ,  0.965],
    [32.   ,  8.   ,  0.962],
    [32.   ,  9.   ,  0.989],
    [32.   , 10.   ,  0.976],
    [32.   , 11.   ,  1.003],
    [32.   , 12.   ,  1.02 ],
    [33.   ,  1.   ,  0.891],
    [33.   ,  2.   ,  0.888],
    [33.   ,  3.   ,  0.975],
    [33.   ,  4.   ,  0.932],
    [33.   ,  5.   ,  0.929],
    [33.   ,  6.   ,  0.976],
    [33.   ,  7.   ,  0.983],
    [33.   ,  8.   ,  0.97 ],
    [33.   ,  9.   ,  0.957],
    [33.   , 10.   ,  1.014],
    [33.   , 11.   ,  0.981],
    [33.   , 12.   ,  1.048],
    [34.   ,  1.   ,  0.929],
    [34.   ,  2.   ,  0.986],
    [34.   ,  3.   ,  0.943],
    [34.   ,  4.   ,  0.93 ],
    [34.   ,  5.   ,  0.967],
    [34.   ,  6.   ,  0.974],
    [34.   ,  7.   ,  1.021],
    [34.   ,  8.   ,  0.978],
    [34.   ,  9.   ,  1.045],
    [34.   , 10.   ,  0.972],
    [34.   , 11.   ,  0.979],
    [34.   , 12.   ,  0.986],
    [35.   ,  1.   ,  1.027],
    [35.   ,  2.   ,  0.964],
    [35.   ,  3.   ,  1.041],
    [35.   ,  4.   ,  1.048],
    [35.   ,  5.   ,  1.065],
    [35.   ,  6.   ,  0.972],
    [35.   ,  7.   ,  0.979],
    [35.   ,  8.   ,  1.036],
    [35.   ,  9.   ,  0.993],
    [35.   , 10.   ,  1.07 ],
    [35.   , 11.   ,  1.017],
    [35.   , 12.   ,  1.014],
    [36.   ,  1.   ,  1.055],
    [36.   ,  2.   ,  1.052],
    [36.   ,  3.   ,  1.059],
    [36.   ,  4.   ,  0.986],
    [36.   ,  5.   ,  1.023],
    [36.   ,  6.   ,  1.05 ],
    [36.   ,  7.   ,  1.047],
    [36.   ,  8.   ,  1.114],
    [36.   ,  9.   ,  1.081],
    [36.   , 10.   ,  1.088],
    [36.   , 11.   ,  1.045],
    [36.   , 12.   ,  1.112],
    [37.   ,  1.   ,  1.003],
    [37.   ,  2.   ,  1.1  ],
    [37.   ,  3.   ,  1.077],
    [37.   ,  4.   ,  1.054],
    [37.   ,  5.   ,  1.021],
    [37.   ,  6.   ,  1.048],
    [37.   ,  7.   ,  1.055],
    [37.   ,  8.   ,  1.112],
    [37.   ,  9.   ,  1.109],
    [37.   , 10.   ,  1.136],
    [37.   , 11.   ,  1.153],
    [37.   , 12.   ,  1.16 ],
    [38.   ,  1.   ,  1.061],
    [38.   ,  2.   ,  1.128],
    [38.   ,  3.   ,  1.135],
    [38.   ,  4.   ,  1.042],
    [38.   ,  5.   ,  1.079],
    [38.   ,  6.   ,  1.056],
    [38.   ,  7.   ,  1.133],
    [38.   ,  8.   ,  1.08 ],
    [38.   ,  9.   ,  1.087],
    [38.   , 10.   ,  1.184],
    [38.   , 11.   ,  1.191],
    [38.   , 12.   ,  1.178],
    [39.   ,  1.   ,  1.049],
    [39.   ,  2.   ,  1.056],
    [39.   ,  3.   ,  1.133],
    [39.   ,  4.   ,  1.15 ],
    [39.   ,  5.   ,  1.127],
    [39.   ,  6.   ,  1.134],
    [39.   ,  7.   ,  1.101],
    [39.   ,  8.   ,  1.188],
    [39.   ,  9.   ,  1.145],
    [39.   , 10.   ,  1.122],
    [39.   , 11.   ,  1.219],
    [39.   , 12.   ,  1.206],
    [40.   ,  1.   ,  1.107],
    [40.   ,  2.   ,  1.134],
    [40.   ,  3.   ,  1.161],
    [40.   ,  4.   ,  1.108],
    [40.   ,  5.   ,  1.135],
    [40.   ,  6.   ,  1.182],
    [40.   ,  7.   ,  1.179],
    [40.   ,  8.   ,  1.226],
    [40.   ,  9.   ,  1.143],
    [40.   , 10.   ,  1.18 ],
    [40.   , 11.   ,  1.237],
    [40.   , 12.   ,  1.194]
])

data

array([[28.   ,  1.   ,  0.801],
       [28.   ,  2.   ,  0.758],
       [28.   ,  3.   ,  0.785],
       [28.   ,  4.   ,  0.862],
       [28.   ,  5.   ,  0.799],
       [28.   ,  6.   ,  0.836],
       [28.   ,  7.   ,  0.783],
       [28.   ,  8.   ,  0.8  ],
       [28.   ,  9.   ,  0.887],
       [28.   , 10.   ,  0.904],
       [28.   , 11.   ,  0.831],
       [28.   , 12.   ,  0.848],
       [29.   ,  1.   ,  0.839],
       [29.   ,  2.   ,  0.836],
       [29.   ,  3.   ,  0.803],
       [29.   ,  4.   ,  0.83 ],
       [29.   ,  5.   ,  0.877],
       [29.   ,  6.   ,  0.884],
       [29.   ,  7.   ,  0.871],
       [29.   ,  8.   ,  0.888],
       [29.   ,  9.   ,  0.915],
       [29.   , 10.   ,  0.912],
       [29.   , 11.   ,  0.859],
       [29.   , 12.   ,  0.876],
       [30.   ,  1.   ,  0.857],
       [30.   ,  2.   ,  0.854],
       [30.   ,  3.   ,  0.841],
       [30.   ,  4.   ,  0.818],
       [30.   ,  5.   ,  0.825],
       [30.   ,  6.   ,  0.852],
       [30

Verifying we sliced $X$ correctly.

In [79]:
X = data[:, 0:2]
X

array([[28.,  1.],
       [28.,  2.],
       [28.,  3.],
       [28.,  4.],
       [28.,  5.],
       [28.,  6.],
       [28.,  7.],
       [28.,  8.],
       [28.,  9.],
       [28., 10.],
       [28., 11.],
       [28., 12.],
       [29.,  1.],
       [29.,  2.],
       [29.,  3.],
       [29.,  4.],
       [29.,  5.],
       [29.,  6.],
       [29.,  7.],
       [29.,  8.],
       [29.,  9.],
       [29., 10.],
       [29., 11.],
       [29., 12.],
       [30.,  1.],
       [30.,  2.],
       [30.,  3.],
       [30.,  4.],
       [30.,  5.],
       [30.,  6.],
       [30.,  7.],
       [30.,  8.],
       [30.,  9.],
       [30., 10.],
       [30., 11.],
       [30., 12.],
       [31.,  1.],
       [31.,  2.],
       [31.,  3.],
       [31.,  4.],
       [31.,  5.],
       [31.,  6.],
       [31.,  7.],
       [31.,  8.],
       [31.,  9.],
       [31., 10.],
       [31., 11.],
       [31., 12.],
       [32.,  1.],
       [32.,  2.],
       [32.,  3.],
       [32.,  4.],
       [32.,

Verifying we sliced $y$ correctly.

In [80]:
y = data[:, [-1]]
y

array([[0.801],
       [0.758],
       [0.785],
       [0.862],
       [0.799],
       [0.836],
       [0.783],
       [0.8  ],
       [0.887],
       [0.904],
       [0.831],
       [0.848],
       [0.839],
       [0.836],
       [0.803],
       [0.83 ],
       [0.877],
       [0.884],
       [0.871],
       [0.888],
       [0.915],
       [0.912],
       [0.859],
       [0.876],
       [0.857],
       [0.854],
       [0.841],
       [0.818],
       [0.825],
       [0.852],
       [0.849],
       [0.876],
       [0.873],
       [0.88 ],
       [0.947],
       [0.964],
       [0.825],
       [0.912],
       [0.909],
       [0.856],
       [0.893],
       [0.91 ],
       [0.867],
       [0.974],
       [0.921],
       [0.888],
       [0.905],
       [0.952],
       [0.943],
       [0.88 ],
       [0.877],
       [0.904],
       [0.891],
       [0.898],
       [0.965],
       [0.962],
       [0.989],
       [0.976],
       [1.003],
       [1.02 ],
       [0.891],
       [0.888],
       [

Displaying the lowest and highest of each of the following:
- certification score
- years experience
- ML rating

In [81]:
# first the lowest of each
np.min(X, axis=0) # 0 = x-axis, 1 = y-axis

array([28.,  1.])

In [82]:
# then the highest of each
np.max(X, axis=0)

array([40., 12.])

Then we scale using Scikit-learn's scaler, which is easier.  We can also use numpy's vectorization, that's one less library to learn.

Note that:
- for certification scores of `40`, they become `1`s, `28` become `0`s.
- for years experience of `1`, they become `0`s, `12` becomes `1`s.

In [83]:
scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)

# Showing the normalized values
X

array([[28.,  1.],
       [28.,  2.],
       [28.,  3.],
       [28.,  4.],
       [28.,  5.],
       [28.,  6.],
       [28.,  7.],
       [28.,  8.],
       [28.,  9.],
       [28., 10.],
       [28., 11.],
       [28., 12.],
       [29.,  1.],
       [29.,  2.],
       [29.,  3.],
       [29.,  4.],
       [29.,  5.],
       [29.,  6.],
       [29.,  7.],
       [29.,  8.],
       [29.,  9.],
       [29., 10.],
       [29., 11.],
       [29., 12.],
       [30.,  1.],
       [30.,  2.],
       [30.,  3.],
       [30.,  4.],
       [30.,  5.],
       [30.,  6.],
       [30.,  7.],
       [30.,  8.],
       [30.,  9.],
       [30., 10.],
       [30., 11.],
       [30., 12.],
       [31.,  1.],
       [31.,  2.],
       [31.,  3.],
       [31.,  4.],
       [31.,  5.],
       [31.,  6.],
       [31.,  7.],
       [31.,  8.],
       [31.,  9.],
       [31., 10.],
       [31., 11.],
       [31., 12.],
       [32.,  1.],
       [32.,  2.],
       [32.,  3.],
       [32.,  4.],
       [32.,

In [84]:
# and the normalized ones
X_norm

array([[0.   , 0.   ],
       [0.   , 0.091],
       [0.   , 0.182],
       [0.   , 0.273],
       [0.   , 0.364],
       [0.   , 0.455],
       [0.   , 0.545],
       [0.   , 0.636],
       [0.   , 0.727],
       [0.   , 0.818],
       [0.   , 0.909],
       [0.   , 1.   ],
       [0.083, 0.   ],
       [0.083, 0.091],
       [0.083, 0.182],
       [0.083, 0.273],
       [0.083, 0.364],
       [0.083, 0.455],
       [0.083, 0.545],
       [0.083, 0.636],
       [0.083, 0.727],
       [0.083, 0.818],
       [0.083, 0.909],
       [0.083, 1.   ],
       [0.167, 0.   ],
       [0.167, 0.091],
       [0.167, 0.182],
       [0.167, 0.273],
       [0.167, 0.364],
       [0.167, 0.455],
       [0.167, 0.545],
       [0.167, 0.636],
       [0.167, 0.727],
       [0.167, 0.818],
       [0.167, 0.909],
       [0.167, 1.   ],
       [0.25 , 0.   ],
       [0.25 , 0.091],
       [0.25 , 0.182],
       [0.25 , 0.273],
       [0.25 , 0.364],
       [0.25 , 0.455],
       [0.25 , 0.545],
       [0.2

In [85]:
model = keras.models.Sequential([
  keras.layers.Dense(units=1, input_shape=[2])
])
model.compile(
  loss=keras.losses.MeanSquaredError(),
  optimizer=keras.optimizers.SGD(learning_rate=0.01)
)
model.fit(X_norm, y, epochs=500)

Epoch 1/500
5/5 [==============================] - 0s 1ms/step - loss: 0.1308
Epoch 2/500
5/5 [==============================] - 0s 1ms/step - loss: 0.1167
Epoch 3/500
5/5 [==============================] - 0s 1ms/step - loss: 0.1062
Epoch 4/500
5/5 [==============================] - 0s 1ms/step - loss: 0.0985
Epoch 5/500
5/5 [==============================] - 0s 1ms/step - loss: 0.0922
Epoch 6/500
5/5 [==============================] - 0s 1ms/step - loss: 0.0875
Epoch 7/500
5/5 [==============================] - 0s 1ms/step - loss: 0.0838
Epoch 8/500
5/5 [==============================] - 0s 1ms/step - loss: 0.0808
Epoch 9/500
5/5 [==============================] - 0s 1ms/step - loss: 0.0783
Epoch 10/500
5/5 [==============================] - 0s 1ms/step - loss: 0.0762
Epoch 11/500
5/5 [==============================] - 0s 1ms/step - loss: 0.0744
Epoch 12/500
5/5 [==============================] - 0s 1ms/step - loss: 0.0729
Epoch 13/500
5/5 [==============================] - 0s 1ms/st

In [86]:
# Showing our training data again, so we can compare
data

array([[28.   ,  1.   ,  0.801],
       [28.   ,  2.   ,  0.758],
       [28.   ,  3.   ,  0.785],
       [28.   ,  4.   ,  0.862],
       [28.   ,  5.   ,  0.799],
       [28.   ,  6.   ,  0.836],
       [28.   ,  7.   ,  0.783],
       [28.   ,  8.   ,  0.8  ],
       [28.   ,  9.   ,  0.887],
       [28.   , 10.   ,  0.904],
       [28.   , 11.   ,  0.831],
       [28.   , 12.   ,  0.848],
       [29.   ,  1.   ,  0.839],
       [29.   ,  2.   ,  0.836],
       [29.   ,  3.   ,  0.803],
       [29.   ,  4.   ,  0.83 ],
       [29.   ,  5.   ,  0.877],
       [29.   ,  6.   ,  0.884],
       [29.   ,  7.   ,  0.871],
       [29.   ,  8.   ,  0.888],
       [29.   ,  9.   ,  0.915],
       [29.   , 10.   ,  0.912],
       [29.   , 11.   ,  0.859],
       [29.   , 12.   ,  0.876],
       [30.   ,  1.   ,  0.857],
       [30.   ,  2.   ,  0.854],
       [30.   ,  3.   ,  0.841],
       [30.   ,  4.   ,  0.818],
       [30.   ,  5.   ,  0.825],
       [30.   ,  6.   ,  0.852],
       [30

How much will we offer?
- another candidate barely passing, with 12 years exp
- another _"kabit"_, but a 15 year veteran?
  * we never had a 15 year veteran apply before
- barely passing also, and with only half a year experience?
- perfect score, 15 years experience
- perfect score, 12 years experience, like the guy offered $119.4k$

In [87]:
scaled_input = scaler.transform(np.array([
    [28, 12], 
    [28, 15],
    [28, 0.5],
    [40, 15],
    [40, 12]
]))

model.predict(scaled_input) * 100_000

array([[ 86130.559],
       [ 89092.261],
       [ 74777.365],
       [126128.817],
       [123167.109]])

In [88]:
model.weights

[<tf.Variable 'dense_6/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[0.37 ],
        [0.109]], dtype=float32)>,
 <tf.Variable 'dense_6/bias:0' shape=(1,) dtype=float32, numpy=array([0.753], dtype=float32)>]